name: Continuous Delivery

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build an app
        run: |
          make build

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: registry.goboolean.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push docker image to registry
        run: |
          docker tag fetch-system/streams:latest registry.goboolean.io/fetch-system/image_name:${GITHUB_SHA::7}
          docker push registry.goboolean.io/fetch-system/image_name:${GITHUB_SHA::7}
